### ISSUE TITLE
Can I emit to another state? 

### ISSUE THREAD

**Issue by minhluyen0702** [hmduc1603/smooth_bloc#1]
I have 3 Uis:
- **sign in form** (SignInCubit - SignInState)
- **sign up form** (SignUpCubit - SignUpState)
- and **animation page** (AuthCubit - AuthState)
[Screen_recording_20240529_152549.webm](https://github.com/hmduc1603/smooth_bloc/assets/40636977/c7739f12-c9c1-48cd-aab4-fba704a43039)

Because **sign in/up form** only included **text field** and **animation page** included **submit button**. 

How can i send onTap() from AuthCubit to SignInCubit?

I try to emit(SignInState) from AuthCubit but prevented.

**Comment by hmduc1603** [comment]
Hi, the concept of BLOC and MVI pattern keep a screen from directly interacting with other's screen lifecycle (Cubit in this case). 
**I assume that  SignInScreen & SignUpScreen are child widgets of AuthScreen, is that right?**

If you could provide widget tree diagram from IDE it could help a lot.

**Comment by minhluyen0702** [comment]
Dear hmduc1603,
Thank you so much for fast responding.

Yes, **SignInScreen**, **SignUpScreen** are child of **AuthScreen**. However, for each screen I use a cubit. Can **smooth_bloc** communicate between 3 cubits?

Best Regards,

![widget_tree_diagram](https://github.com/hmduc1603/smooth_bloc/assets/40636977/276aec8b-700b-42e0-938c-990d15528c8f)

**Comment by hmduc1603** [comment]
You can communicate between cubit if you mark the cubit class as singleton pattern, I usually put @singleton on top the cubit class (GetIt) and call any functions from it, for example getit<SignInCubit>()....
However, be aware of using this method because cubit and state should be disposed together with statefullwidget (screen). By making Cubit singleton, it will existed throughout application life without being closed

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: minhluyen0702 ***@***.***>
Đã gửi: Wednesday, May 29, 2024 4:48:23 PM
Đến: hmduc1603/smooth_bloc ***@***.***>
Cc: Dennis Hoang ***@***.***>; Comment ***@***.***>
Chủ đề: Re: [hmduc1603/smooth_bloc] Can I emit to another state? (Issue #1)


Dear hmduc1603,
Thank you so much for fast responding.

Yes, SignInScreen, SignUpScreen are child of AuthScreen. However, for each screen I use a cubit. Can smooth_bloc communicate between 3 cubits?
widget_tree_diagram.png (view on web)<https://github.com/hmduc1603/smooth_bloc/assets/40636977/276aec8b-700b-42e0-938c-990d15528c8f>

Best Regards,
minhluyen0702

**Comment by minhluyen0702** [comment]
Dear hmduc1603,
Thank you so much for fast responding.

Thanks for your solution it was very helpful. Just like you said "By making Cubit singleton, it will existed throughout application life without being closed". I used Function Close cubit before navigate to another screen to minimize that case. It is obvious that it is created from the initial run app to be inevitable.

Best Regards,
